version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/eink_layout_manager"
    schedule:
      interval: "daily"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/eink_layout_manager/app"
    schedule:
      interval: "daily"
    groups:
      python-dependencies:
        patterns:
          - "*"
