version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/eink_layout_manager"
    schedule:
      interval: "daily"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/eink_layout_manager/backend"
    schedule:
      interval: "daily"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/eink_layout_manager/frontend"
    schedule:
      interval: "daily"
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/eink_layout_manager/e2e"
    schedule:
      interval: "daily"
    groups:
      e2e-dependencies:
        patterns:
          - "*"
