name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking change'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: '🐍 Python Changes'
    labels:
      - 'python'
  - title: '🎨 Frontend Changes'
    labels:
      - 'frontend'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking change'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch
template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: 'breaking change'
    title:
      - '/\!:/'
  - label: 'feature'
    title:
      - '/^feat:/i'
      - '/feature/i'
      - '/enhancement/i'
    branch:
      - '/^feature\//i'
      - '/^feat\//i'
      - '/^enhancement\//i'
  - label: 'fix'
    title:
      - '/^fix:/i'
      - '/bugfix/i'
      - '/\bfix\b/i'
    branch:
      - '/^fix\//i'
      - '/^bugfix\//i'
  - label: 'chore'
    title:
      - '/^chore:/i'
      - '/^ci:/i'
      - '/^test:/i'
      - '/^refactor:/i'
      - '/^docs:/i'
    branch:
      - '/^chore\//i'
      - '/^ci\//i'
      - '/^test\//i'
      - '/^refactor\//i'
      - '/^docs\//i'
  - label: 'python'
    files:
      - 'eink_layout_manager/app/**/*.py'
      - 'eink_layout_manager/Dockerfile'
  - label: 'frontend'
    files:
      - 'eink_layout_manager/app/static/**/*'
