name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Addon
        uses: home-assistant/builder@master
        with:
          args: --amd64 --target /data/addon --docker-hub ghcr.io/stuart-c
