name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Addon
        if: github.ref == 'refs/heads/main'
        uses: home-assistant/builder@master
        with:
          args: --amd64 --aarch64 --armv7 --target /data/eink_layout_manager --docker-hub ghcr.io/stuart-c

      - name: Test Build Addon
        if: github.ref != 'refs/heads/main'
        uses: home-assistant/builder@master
        with:
          args: --amd64 --aarch64 --armv7 --target /data/eink_layout_manager --test
