name: Python Lint

on: pull_request

permissions:
  contents: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Python Code
    steps:
      - name: Check out source repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python environment
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Install linting tools
        run: pip install flake8==7.3.0 flake8-pyproject==1.2.3 flake8-docstrings flake8-simplify flake8-unused-arguments flake8-quotes flake8-bugbear black==26.3.1

      - name: flake8 Lint
        uses: reviewdog/action-flake8@b65981e158319f08cb7d0132f28bc0081e110adc # v3.15.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: eink/backend
          fail_level: any

      - name: black Lint
        uses: reviewdog/action-black@9b4feb439b707a9b7673086795cc53e417a03abe # v3.23.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          workdir: eink/backend
          fail_level: any
