name: Python Lint

on: pull_request

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Python Code
    steps:
      - name: Check out source repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python environment
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Install linting tools
        run: pip install flake8==7.3.0 flake8-pyproject==1.2.3 flake8-docstrings flake8-simplify flake8-unused-arguments flake8-quotes flake8-bugbear black==26.3.1

      - name: flake8 Lint
        uses: reviewdog/action-flake8@b65981e158319f08cb7d0132f28bc0081e110adc # v3.15.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: eink_layout_manager/backend

      - name: black Lint
        uses: reviewdog/action-black@644053a260402bc4278a865906107bd8aef7fae8 # v3.22.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning
          workdir: eink_layout_manager/backend
