name: Python Lint

on: pull_request

permissions:
  contents: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Python Code
    steps:
      - name: Check out source repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python environment
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Install linting tools
        run: pip install flake8==7.3.0 flake8-pyproject==1.2.3 flake8-docstrings flake8-simplify flake8-unused-arguments flake8-quotes flake8-bugbear black==26.3.1

      - name: flake8 Lint
        uses: reviewdog/action-flake8@b65981e158319f08cb7d0132f28bc0081e110adc # v3.15.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: eink/backend
          fail_level: any

      - name: black Lint
        uses: reviewdog/action-black@9b4feb439b707a9b7673086795cc53e417a03abe # v3.23.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          workdir: eink/backend
          fail_level: any
